version: "3.8"

services:
  discord-bot:
    build: .
    image: poseidon-bot:latest
    container_name: poseidon-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./scripts:/app/scripts
      - /:/host:ro
    pid: "host"
